---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:1.21.*
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com:tossmilestone/flux-get-started
    ref: master
    path: charts/ghost
  values:
    ghostHost: blog
    image: bitnami/ghost:2.31.0
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    serviceType: ClusterIP
    mariadb:
      persistence:
        enabled: false
